"""Customer-owned signed control endpoint with a durable action ledger.

This example runs a supplied application function; it never accepts executable
code, credentials, tool arguments, or business input from a webhook. See
CONTROL_ADAPTER.md for deployment and crash-reconciliation responsibilities.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
import hashlib
import hmac
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
import os
from pathlib import Path
import sqlite3
import threading
import time
from typing import Any, Awaitable, Callable

from watchdog_agent import Run, Watchdog


MAX_BODY = 65536


class ControlError(Exception):
    def __init__(self, status: int, message: str):
        self.status, self.message = status, message


class ActionLedger:
    """Persist before dispatch; duplicate requests never dispatch twice.

An uncertain action after a process crash needs explicit reconciliation with
the customer's durable runtime. Blindly rerunning it would duplicate work.
"""

    def __init__(self, path: str):
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        self.db = sqlite3.connect(path)
        self.db.execute("PRAGMA journal_mode=WAL")
        self.db.execute("PRAGMA synchronous=FULL")
        self.db.execute("CREATE TABLE IF NOT EXISTS actions (id TEXT PRIMARY KEY, digest TEXT NOT NULL, state TEXT NOT NULL, response TEXT, created_at INTEGER NOT NULL)")
        self.db.execute("UPDATE actions SET state='uncertain' WHERE state='dispatching'")
        self.db.commit()

    def claim(self, action_id: str, digest: str) -> dict | None:
        with self.db:
            row = self.db.execute("SELECT digest,state,response FROM actions WHERE id=?", (action_id,)).fetchone()
            if row:
                if not hmac.compare_digest(row[0], digest):
                    raise ControlError(409, "Action ID was already used for a different command")
                if row[1] in {"dispatching", "uncertain"}:
                    raise ControlError(409, "Action dispatch requires reconciliation with the customer runtime")
                return json.loads(row[2])
            self.db.execute("INSERT INTO actions(id,digest,state,created_at) VALUES(?,?,?,?)", (action_id, digest, "dispatching", int(time.time())))
        return None

    def finish(self, action_id: str, response: dict) -> None:
        with self.db:
            self.db.execute("UPDATE actions SET state='accepted', response=? WHERE id=?", (json.dumps(response), action_id))

    def close(self) -> None:
        self.db.close()


def authenticate(secret: bytes, headers: dict[str, str], body: bytes, *, now: float | None = None, max_age: int = 300) -> None:
    headers = {name.lower(): value for name, value in headers.items()}
    timestamp = headers.get("x-watchdog-timestamp", "")
    signature = headers.get("x-watchdog-signature", "")
    if len(body) > MAX_BODY:
        raise ControlError(413, "Request body is too large")
    if not timestamp.isascii() or not timestamp.isdigit() or len(timestamp) > 12:
        raise ControlError(401, "Invalid signature timestamp")
    if abs((time.time() if now is None else now) - int(timestamp)) > max_age:
        raise ControlError(401, "Signature timestamp is outside the allowed window")
    if not signature.isascii() or not signature.startswith("v1=") or len(signature) != 67:
        raise ControlError(401, "Invalid webhook signature")
    expected = "v1=" + hmac.new(secret, timestamp.encode("ascii") + b"." + body, hashlib.sha256).hexdigest()
    if not hmac.compare_digest(expected, signature):
        raise ControlError(401, "Invalid webhook signature")


@dataclass
class ActiveRun:
    run: Run
    task: asyncio.Task


class ControlAdapter:
    def __init__(
        self,
        watchdog: Watchdog,
        secret: str,
        ledger_path: str,
        *,
        load_input: Callable[[str, str | None, str | None], Any],
        execute: Callable[[str, Any, Run, str | None], Awaitable[None]],
        allowed_jobs: set[str],
        allowed_fallback_models: set[str] | None = None,
        max_active_runs: int = 32,
    ):
        if len(secret) < 32:
            raise ValueError("Use the signing secret generated by Watchdog Settings")
        self.watchdog, self.secret = watchdog, secret.encode()
        self.ledger = ActionLedger(ledger_path)
        self.load_input, self.execute = load_input, execute
        self.allowed_jobs = set(allowed_jobs)
        self.allowed_fallback_models = set(allowed_fallback_models or ())
        self.max_active_runs = max_active_runs
        self.active: dict[str, ActiveRun] = {}

    async def close(self) -> None:
        tasks = [active.task for active in self.active.values()]
        for task in tasks:
            task.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)
        self.ledger.close()

    async def start(self, job_id: str, payload: Any, *, metadata: dict | None = None, fallback_model: str | None = None) -> str:
        """Start customer-owned work from trusted local input, including initial runs."""
        if job_id not in self.allowed_jobs or len(self.active) >= self.max_active_runs:
            raise ControlError(409, "Job is not allowed or runtime capacity is full")
        if fallback_model is not None and fallback_model not in self.allowed_fallback_models:
            raise ControlError(400, "Fallback model is not allowed by this customer runtime")
        run = self.watchdog.run(job_id, cancellable=True, metadata=metadata)
        started = asyncio.Event()

        async def work() -> None:
            async with run:
                started.set()
                await self.execute(job_id, payload, run, fallback_model)

        task = asyncio.create_task(work(), name="watchdog-job-" + run.id)
        self.active[run.id] = ActiveRun(run, task)

        def completed(finished: asyncio.Task) -> None:
            self.active.pop(run.id, None)
            # Consume the exception without logging potentially sensitive messages.
            if not finished.cancelled():
                finished.exception()

        task.add_done_callback(completed)
        await started.wait()
        return run.id

    async def handle(self, body: bytes, headers: dict[str, str]) -> tuple[int, dict]:
        """Verify, durably deduplicate, and dispatch on the owning asyncio loop."""
        claimed_action = None
        try:
            authenticate(self.secret, headers, body)
            try:
                command = json.loads(body)
            except (ValueError, UnicodeDecodeError):
                raise ControlError(400, "Expected a JSON object")
            if not isinstance(command, dict):
                raise ControlError(400, "Expected a JSON object")
            action_id = command.get("action_id")
            job_id, kind, run_id = command.get("job_id"), command.get("command"), command.get("run_id")
            if not isinstance(action_id, str) or not action_id or len(action_id) > 200:
                raise ControlError(400, "Invalid action ID")
            if not isinstance(job_id, str) or job_id not in self.allowed_jobs:
                raise ControlError(400, "Job is not allowed by this customer runtime")
            if not isinstance(kind, str) or kind not in {"cancel", "retry"}:
                raise ControlError(400, "Unsupported command")
            if run_id is not None and (not isinstance(run_id, str) or not run_id or len(run_id) > 200):
                raise ControlError(400, "Invalid run ID")
            if kind == "cancel" and run_id is None:
                raise ControlError(400, "Cancellation requires a run ID")
            fallback_model = command.get("fallback_model")
            if fallback_model is not None and (not isinstance(fallback_model, str) or fallback_model not in self.allowed_fallback_models):
                raise ControlError(400, "Fallback model is not allowed by this customer runtime")
            scheduled_at = command.get("scheduled_at")
            if scheduled_at is not None and not isinstance(scheduled_at, str):
                raise ControlError(400, "Invalid schedule slot")
            if kind == "retry" and run_id is None and not scheduled_at:
                raise ControlError(400, "A missed-run retry requires its scheduled slot")
            previous = self.ledger.claim(action_id, hashlib.sha256(body).hexdigest())
            if previous is not None:
                return 202, {**previous, "duplicate": True}
            claimed_action = action_id

            response = {"accepted": True, "action_id": action_id}
            if kind == "cancel":
                active = self.active.get(run_id)
                if active is None or active.run.job != job_id:
                    self.watchdog._ack(action_id, "failed", "Run is not active on this customer runtime")
                    response["accepted"] = False
                else:
                    # The run context emits run.cancelled then ACK only after it exits.
                    active.run._command(command)
            else:
                # The webhook carries no executable code or business payload.
                payload = self.load_input(job_id, run_id, scheduled_at)
                metadata = {key: command[key] for key in ("action_id", "root_run_id", "retry_number", "scheduled_at") if command.get(key) is not None}
                if run_id is not None:
                    metadata["parent_run_id"] = run_id
                new_id = await self.start(job_id, payload, metadata=metadata, fallback_model=fallback_model)
                response["run_id"] = new_id
                # start() has enqueued run.started before this ACK enters the FIFO queue.
                self.watchdog._ack(action_id, "acknowledged", "Customer runtime started the retry")
            self.ledger.finish(action_id, response)
            return 202, response
        except ControlError as error:
            if claimed_action is not None:
                response = {"accepted": False, "action_id": claimed_action, "error": error.message}
                self.watchdog._ack(claimed_action, "failed", error.message)
                self.ledger.finish(claimed_action, response)
                return 202, response
            return error.status, {"error": error.message}
        except Exception:
            # Do not disclose customer input or exception text. An uncertain ledger
            # claim prevents automatically duplicating partially dispatched work.
            return 500, {"error": "Dispatch failed; reconcile the action with the customer runtime"}


def create_http_server(adapter: ControlAdapter, loop: asyncio.AbstractEventLoop, *, host: str = "127.0.0.1", port: int = 8090) -> ThreadingHTTPServer:
    """Bind behind a TLS reverse proxy; call serve_forever in a dedicated thread."""
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *args):
            pass  # Do not log raw headers, signatures, or webhook bodies.

        def do_POST(self):
            if self.path != "/watchdog/control":
                self.send_error(404)
                return
            if self.headers.get("Transfer-Encoding"):
                self.send_error(400, "Chunked request bodies are not accepted")
                return
            try:
                length = int(self.headers.get("Content-Length", "0"))
            except ValueError:
                length = 0
            if length <= 0 or length > MAX_BODY:
                self.send_error(413 if length > MAX_BODY else 411)
                return
            self.connection.settimeout(5)
            try:
                body = self.rfile.read(length)
                if len(body) != length:
                    self.send_error(400)
                    return
                future = asyncio.run_coroutine_threadsafe(adapter.handle(body, dict(self.headers)), loop)
                status, response = future.result(timeout=5)
            except Exception:
                status, response = 503, {"error": "Customer runtime temporarily unavailable"}
            encoded = json.dumps(response).encode()
            self.send_response(status)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(encoded)))
            self.end_headers()
            self.wfile.write(encoded)

    return ThreadingHTTPServer((host, port), Handler)


async def main() -> None:
    """Runnable local demo. Replace load_input/execute with your application's code."""
    report_directory = Path(os.getenv("WATCHDOG_REPORT_DIR", "work/control-demo/reports"))
    report_directory.mkdir(parents=True, exist_ok=True)

    def load_input(job_id: str, parent_run_id: str | None, scheduled_at: str | None) -> dict:
        # In a real application, read immutable business input from your own store.
        return {"records": ["Example A", "Example B", "Example C"], "scheduled_at": scheduled_at}

    async def execute(job_id: str, payload: dict, run: Run, fallback_model: str | None) -> None:
        # No model or external service is called in this demonstration.
        for number in range(10):
            await asyncio.sleep(2)
            run.progress("Processing demo report", completed=number + 1, total=10)
        report = {"run_id": run.id, "records": payload["records"], "scheduled_at": payload.get("scheduled_at")}
        (report_directory / (run.id + ".json")).write_text(json.dumps(report, indent=2))
        run.outcome("report_created", metadata={"record_id": run.id})

    async with Watchdog() as watchdog:
        adapter = ControlAdapter(
            watchdog,
            os.environ["WATCHDOG_SIGNING_SECRET"],
            os.getenv("WATCHDOG_ACTION_LEDGER", "work/control-demo/actions.sqlite3"),
            load_input=load_input,
            execute=execute,
            allowed_jobs={"daily-report"},
        )
        server = create_http_server(adapter, asyncio.get_running_loop(), port=int(os.getenv("WATCHDOG_CONTROL_PORT", "8090")))
        thread = threading.Thread(target=server.serve_forever, daemon=True, name="watchdog-control-http")
        thread.start()
        try:
            run_id = await adapter.start("daily-report", load_input("daily-report", None, None))
            print("Control endpoint listening on loopback /watchdog/control; initial run:", run_id)
            await asyncio.Event().wait()
        finally:
            await asyncio.to_thread(server.shutdown)
            server.server_close()
            await adapter.close()


if __name__ == "__main__":
    asyncio.run(main())
